{% extends "layout.swig" %}

{% block title %}Background Stallion Sources{% endblock %}
{% block body %}
<div class="jumbotron">
<h1>Links</h1>
</div>
<section>
	<ul>	
		<li><a href="https://www.deviantart.com/cloudyglow/art/Sleeping-Sandbar-770849384">Sleeping Sandbar</a></li>
		<li><a href="https://www.deviantart.com/cloudyglow/art/Wide-eyed-Sunburst-721059547">Wide-eyed Sunburst</a></li>
		<li><a href="https://www.deviantart.com/chainchomp2/art/Nervous-Thunderlane-416826041">Nervous Thunderlane</a></li>
		<li><a href="https://www.deviantart.com/chainchomp2/art/Revealed-Mac-640459689">Revealed Mac</a></li>
		<li><a href="https://www.deviantart.com/chainchomp2/art/Marchingworthy-439195905">Marchingworthy</a></li>
		<li><a href="https://www.deviantart.com/chainchomp2/art/Awestruck-Whooves-460379533">Awestruck Whooves</a></li>
		<li><a href="https://www.deviantart.com/sakatagintoki117/art/Shining-Armor-339746794">Shining Armor</a></li>
	</ul>
</section>
{% include "nav.swig" %}
{% endblock %}
